language: python
os:
  - linux
  - windows
  # - osx
python :
  - "3.7"
  - "3.8"
  #- "3.9"
  - "nightly"
  # - "pypy3"
install:
  - pip install -r requirements.txt
  - python setup.py -q install
script:
  - pytest
notifications:
  email: true
branches:
  only:
  - master
  - xml-schema-revision
  - /v(\d+)\.(\d+)\.*/
matrix:
  allow_failures:
  - python: nightly
codecov: true
