name: Build and Release

on:
  push:
    # Only trigger on pushes to a specific branch
    branches:
      - 'releases'  # Change this to your desired branch name
    # Optionally keep tag triggers if you want both options
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://pdm-project.org/install-pdm.py | python3 -
          
      - name: Sync deps and build
        run: |
          pdm sync --no-self
          pdm build
        
      - name: Create Release from Tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          draft: false
          prerelease: false
          
      - name: Create Release from Branch
        if: github.ref == 'refs/heads/releases'  # Only create releases from the specified branch
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          draft: false
          prerelease: true
          tag_name: branch-release.${{ github.sha }}
          name: "Release from releases branch - ${{ github.sha }}"