name: Run Tests and Coverage for OPGEE
run-name: ${{ github.actor }} is running unit tests
on:
  push:
    branches: ['feat/github-actions']

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    env:
      OPGEE_HOME: ${{ github.workspace }}/tests/files

    steps:
    - uses: actions/checkout@v4
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: opgee
        environment-file: ${{ github.workspace }}/py3-opgee-linux.yml
        python-version: 3.9
        auto-activate-base: false
    - name: Install dependencies
      run: |
        python -m pip install .
        pip install pytest-cov codecov coveralls PyYAML

    - name: Run unit tests with coverate
      run: coverage run --source=opgee -m pytest
    - name: Code coverage report
      if: ${{ success() }}
      run: |
        coveralls
        bash <(curl -s https://codecov.io/bash)